title: "SALCAN Process Technology"
email: "info@salcanpt.com"
description: >- # this means to ignore newlines until "baseurl:"
 SALCAN Process Technology is an Electrical Engineering consultancy and a Licensed Electrical Contractor.
 We seek to understand the needs of our clients to deliver safe, compliant, cost effective designs and services. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com or  https://tradejk.netlify.com
facebook_url: https://www.facebook.com/salcanpt
twitter_url: https://twitter.com/salcanpt
github_url:  https://github.com/salcanpt
pinterest_url: https://www.pinterest.com/salcanpt
linkedin_url: https://www.linkedin.com/company/salcan-process-technology/
instagram_url: https://www.instagram.com/salcanpt
logo: "/assets/img/logo/SALCAN Logo - White.png"
logo_2: "/assets/img/logo/logo-sc.png"
mailchimp_list: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=342411fb35"
mailchimp_input_name: "b_307862c135e4548eecf86f389_342411fb35"

permalink: "/:title"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives

cover_image: "/assets/img/bg/page-title.jpg"

#salcan data added by craig
salcan:
  footertext: "Automating your business."
  full_address: "7/80 Ebbern St, Darra QLD 4076"
  map: "/assets/img/map_salcan2.png" 
  office_hours: "Mon - Fri 7:00 am - 5:00 PM"
  enquiry_phone: "Mon - Fri 7:00 am - 5:00 PM"
  send_an_email: "Send us and email and we will get back to you as soon as possible."
  header_address: "Darra QLD 4076"
  header_phone: "1800 SALCAN"
  header_email: "info@salcanpt.com"

  #The words on the basic pages
  careers: Contact us now for opportunities in Electrical Engieering and Control Systems Integration.
  casestudies: Below are some exmaple cases studies to consider.
  industries:
    energy: >- # this means to ignore newlines, you still need to indent
      SALCAN provides design, construction, integration, commissioning and maintenance services across multiple fuel 
      terminals in Queensland, New South Wales and Victoria.
    oilandgas: >- # this means to ignore newlines, you still need to indent
      SALCAN provides design and construction services for gas compression and metering facilities.<br>
      We also provide telemetry solutions and SCADA solutions for remote production and testing sites. 
      This includes telemetry solutions using LTE and satellite technology. 
    mining: >- # this means to ignore newlines, you still need to indent
      SALCAN provides Low Voltage design and lighting design services for maintenance facilities at several QLD mines.<br>
      SALCAN also provides design and construction services for mill reline and transport equipment. 
    defence: >- # this means to ignore newlines, you still need to indent
      SALCAN has delivered projects and maintenance services across multiple Defence locations in Queensland, New South Wales and the Northern Territory.<br>
      Services include periodic maintenance and inspections for maintenance hangars, and the maintenance of PFAS treatment facilities
    foodandbeverage: >- # this means to ignore newlines, you still need to indent
      SALCAN provides control system design and integration services for some of Australia’s largest refrigerated warehouse facilities. 
                                
    
    

  
  #The three sliders on the home page
  slider1:
    comment: "Meet with us to <br>discuss your <span>project</span>"
    subcomment: "We can assist you in defining your objectives to ensure a successful outcome."
  slider2:
    comment: "Meet with us to <br>discuss your <span>design requirements</span>"
    subcomment: "Brown-fields or green-fields, we will work with you towards the most elegant solutions."
  slider3:
    comment: "Meet with us to <br>discuss your <span>maintenance needs</span>"
    subcomment: "Our E&I Technical Services team can assist you with your preventative and reactive maintenance needs."

  #The content under the slider on the home page.
  home_p1:
    title: "SALCAN Process Technology"
    body: >- # this means to ignore newlines, you still need to indent
      SALCAN Process Technology is an Electrical Engineering consultancy and a Licensed Electrical
      Contractor (QLD Licence number 76502). We seek to understand the needs of our clients and to deliver safe, compliant, cost
      effective designs and services. 
  home_p2:
    title: "Process Control and Automation"
    body: >- # this means to ignore newlines, you still need to indent
      Innovative process control solutions are a core focus at SALCAN Process Technology. We
      have a proven track record for delivering robust hardware and software platforms. From
      platform selection, panel design, construction and integration, we have a wealth of
      experience across multiple industries.
      Choosing the right instrumentation and final elements is crucial to the success of an
      automation system.
  home_p3:
    title: "Hazardous Areas"
    body: >- # this means to ignore newlines, you still need to indent
      SALCAN has proven expertise where Hazardous Areas are present. Sectors include Oil & Gas, Mining,
      Manufacturing and Defence. SALCAN employs Engineers,
      Technicians and Electricians who are trained and competent in all aspects of Hazardous
      Area classification, design, installation, inspection and maintenance.
    

#collections
collections:
  features:
    output: true
  services:
    output: true
  capabilities:
    output: true

########################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination page
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 6

  # The permalink structure for the paginated pages (this can be any level deep)
  #permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  permalink: '/pages/blog/:num/' # Pages are simple html file
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: 'html'

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'

feed:
  collections:
    posts:
      path: "/index.xml"
